[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
chrono.workspace = true
serde.workspace = true
kernel.workspace = true
shared.workspace = true
registry.workspace = true
